import { getUser } from "@/actions/server/user.controllers";
import { ThemeProvider } from "@/components/global/theme-provider";
import { ThemeSync } from "@/components/global/theme-sync";
import { Toaster } from "@/components/ui/sonner";

import { domAnimation, LazyMotion } from "motion/react";
import type { Metadata } from "next";
import { Fira_Code, Lato, Nunito } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";

const nunito = Nunito({
 variable: "--font-sans",
 subsets: ["latin"],
 fallback: ["sans-serif"],
});

const lato = Lato({
 variable: "--font-serif",
 subsets: ["latin"],
 weight: ["400", "700"],
 fallback: ["serif"],
});

const firaCode = Fira_Code({
 variable: "--font-mono",
 subsets: ["latin"],
 fallback: ["monospace"],
});

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default async function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 const user = await getUser();
 const userTheme = user?.preferences?.theme;

 return (
  <html lang="en" suppressHydrationWarning>
   <head>
    <script
     crossOrigin="anonymous"
     src="//unpkg.com/react-scan/dist/auto.global.js"
    />
   </head>
   <body
    className={`${nunito.variable} ${firaCode.variable} ${lato.variable} antialiased`}>
    <NuqsAdapter>
     <ThemeProvider
      attribute="class"
      defaultTheme="light"
      enableSystem
      themes={["light", "dark", "rose", "blue", "green"]}
      disableTransitionOnChange>
      <ThemeSync userTheme={userTheme} />
      <LazyMotion features={domAnimation} strict>
       {children}
      </LazyMotion>
      <Toaster />
     </ThemeProvider>
    </NuqsAdapter>
   </body>
  </html>
 );
}
